"""initial schema

Revision ID: a44c3eb848c8
Revises: 
Create Date: 2026-07-07 13:38:39.028232
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op



revision: str = 'a44c3eb848c8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acquisition', sa.Enum('api', 'browser', 'stub', name='acquisition'), nullable=False),
    sa.Column('source_preferences', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_org_id'), ['org_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('primary_domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'archived', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_client_id'), ['client_id'], unique=False)

    op.create_table('brand_entity',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_entity_project_id'), ['project_id'], unique=False)

    op.create_table('citation_run',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('samples', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engine_id'], ['engine.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citation_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_run_engine_id'), ['engine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_citation_run_project_id'), ['project_id'], unique=False)

    op.create_table('deliverable',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('audit_report', 'sov_report', 'content_plan', name='deliverablekind'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deliverable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliverable_project_id'), ['project_id'], unique=False)

    op.create_table('page',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('content_snapshot', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_project_id'), ['project_id'], unique=False)

    op.create_table('prompt',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intent', sa.Enum('branded', 'category', 'problem', 'comparison', name='promptintent'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_project_id'), ['project_id'], unique=False)

    op.create_table('visibility_score',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period', sa.DateTime(), nullable=False),
    sa.Column('entity_sov', sa.Float(), nullable=False),
    sa.Column('citation_sov', sa.Float(), nullable=False),
    sa.Column('avg_rank', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['engine_id'], ['engine.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visibility_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visibility_score_engine_id'), ['engine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visibility_score_project_id'), ['project_id'], unique=False)

    op.create_table('audit_run',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('engine_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engine_id'], ['engine.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_run_page_id'), ['page_id'], unique=False)

    op.create_table('citation_result',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('citation_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('brand_mentioned', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('cited_urls', sa.JSON(), nullable=True),
    sa.Column('own_domain_cited', sa.Boolean(), nullable=False),
    sa.Column('sentiment', sa.Enum('positive', 'neutral', 'negative', name='sentiment'), nullable=True),
    sa.ForeignKeyConstraint(['citation_run_id'], ['citation_run.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citation_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citation_result_citation_run_id'), ['citation_run_id'], unique=False)

    op.create_table('recommendation',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dimension', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('high', 'medium', 'low', name='severity'), nullable=False),
    sa.Column('jsonld', sa.JSON(), nullable=True),
    sa.Column('compliance_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_audit_run_id'), ['audit_run_id'], unique=False)

    op.create_table('score',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_audit_run_id'), ['audit_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_audit_run_id'))

    op.drop_table('score')
    with op.batch_alter_table('recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_audit_run_id'))

    op.drop_table('recommendation')
    with op.batch_alter_table('citation_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citation_result_citation_run_id'))

    op.drop_table('citation_result')
    with op.batch_alter_table('audit_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_run_page_id'))

    op.drop_table('audit_run')
    with op.batch_alter_table('visibility_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visibility_score_project_id'))
        batch_op.drop_index(batch_op.f('ix_visibility_score_engine_id'))

    op.drop_table('visibility_score')
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_project_id'))

    op.drop_table('prompt')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_project_id'))

    op.drop_table('page')
    with op.batch_alter_table('deliverable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliverable_project_id'))

    op.drop_table('deliverable')
    with op.batch_alter_table('citation_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citation_run_project_id'))
        batch_op.drop_index(batch_op.f('ix_citation_run_engine_id'))

    op.drop_table('citation_run')
    with op.batch_alter_table('brand_entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_entity_project_id'))

    op.drop_table('brand_entity')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_client_id'))

    op.drop_table('project')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_org_id'))

    op.drop_table('client')
    op.drop_table('organization')
    op.drop_table('engine')
    # ### end Alembic commands ###
